# Generated by Django 4.2.7 on 2023-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_rename_nome_cliente_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
