# Generated by Django 4.2.7 on 2023-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.EmailField(default="", max_length=11, unique=True),
        ),
    ]
