# Generated by Django 4.2.7 on 2023-11-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(default="", max_length=11, unique=True),
        ),
    ]
