# Generated by Django 4.2.7 on 2023-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_alter_cliente_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rg",
            field=models.CharField(default="", max_length=9),
        ),
    ]
