# Generated by Django 4.2.7 on 2023-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_alter_cliente_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(default="", max_length=150, unique=True),
        ),
    ]
