# Generated by Django 4.2.7 on 2023-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_alter_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(default="", max_length=14),
        ),
    ]
